artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/uurcelikk/ML_Basics/blob/main/dataset.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATS_FILE: artifacts/data_validation/status.txt
  ALL_RECORDS_FILE: ["train","test","validation"]